name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Setup pnpm
      run: |
        npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Create .env.production file
      run: |
        echo "VITE_MAPTILER_API_KEY=${{ secrets.VITE_MAPTILER_API_KEY }}" > .env.production
          
    - name: Build Project
      run: pnpm run build

    - name: Remove .env.production file
      run: rm .env.production
        
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Disable Strict Host Key Checking
      run: |
        mkdir -p ~/.ssh
        echo "Host *" > ~/.ssh/config
        echo "    StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Deploy to VPS
      run: |
        scp -r dist/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/PWA/
