name: Build and Deploy PWA
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Project
      run: npm run build
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          cd /var/www/PWA
          rm -rf *
          mkdir -p /var/www/PWA
          cp -r ${{ github.workspace }}/dist/* /var/www/PWA/
          sudo systemctl restart nginx
    - name: Debug SSH
      run: |
        ssh-keygen -R ${{ secrets.VPS_HOST }}
        ssh-keyscan -t rsa ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
